spring:
  application:
    name: ENTREPRISE-SERVICE

eureka:
  instance:
    appname: ENTREPRISE-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/