global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'entreprise-service'
    metrics_path: '/api/v1/entreprise-service/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.137.1:8083']
  - job_name: 'client-service'
    metrics_path: '/api/v1/client-service/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.137.1:8082']