spring:
  application:
    name: COMMISSION-SERVICE


  #h2:
  #  console.path: /h2-console
  #  console.enabled: true
  #  console.settings.trace: false
  #  spring.h2.console.settings.web-allow-others: false
  datasource:
    url:  jdbc:postgresql://db.qrwvmkaiazrwlwoyxfgq.supabase.co:5432/postgres
    username: postgres
    password: abdelati470952
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    url:  jdbc:postgresql://db.qrwvmkaiazrwlwoyxfgq.supabase.co:5432/postgres
    user: postgres
    password: abdelati470952

logging:
  level:
    "liquibase" : info

liquibase:
  outputChangeLogFile: src/main/resources/db/changelog/changelog-1.0.0.xml
  changeLogFile: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8089


zipkin:
  base-url: http://localhost:9411/